# Generated by Django 3.0.1 on 2019-12-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
