# Generated by Django 3.0.1 on 2019-12-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='day',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
